# Generated by Django 4.1.1 on 2022-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_images_product_category_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('txtarea', models.TextField()),
            ],
        ),
    ]
