# Generated by Django 4.1.1 on 2022-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemsJson', models.CharField(max_length=1100)),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('mobilenumber', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.IntegerField(max_length=10)),
            ],
        ),
    ]
