# Generated by Django 4.1.1 on 2022-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orders_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
